version: '2.1'

services:

  tronmon:
    build: ./tronmon
    privileged: true
    network_mode: host
    restart: always
  
  # ------------------------------------------------------------------------------------
  # MQTT broker 
  # ------------------------------------------------------------------------------------
  mqtt:
    image: eclipse-mosquitto
    network_mode: host
    ports:
      - "1883:1883"
    restart: always
  
  # ------------------------------------------------------------------------------------
  # Influxdb
  # ------------------------------------------------------------------------------------
  influxdb:
    image: influxdb:1.7.11
    container_name: influxdb
    restart: unless-stopped
    ports:
        - '8086'
    volumes:
        - influxdb-data:/var/lib/influxdb
        - influxdb-etc:/etc/influxdb


  # ------------------------------------------------------------------------------------
  # Node-RED
  # ------------------------------------------------------------------------------------
  node-red:
    build: ./node-red 
    privileged: true
    network_mode: host
    restart: unless-stopped
    volumes:
        - 'node-red-data:/data'
    labels:
        io.balena.features.dbus: '1'
        io.balena.features.sysfs: '1'
        io.balena.features.supervisor-api: '1'
        io.balena.features.balena-api: '1'
        io.balena.features.balena-socket: '1'
        io.balena.features.kernel-modules: '1'
        io.balena.features.firmware: '1'
    ports:
        - 80:80
    environment:
        - PORT=80
        - USERNAME="balena"
        - PASSWORD="balena"
        - ENCRIPTION_KEY="balena"
    cap_add:
        - SYS_RAWIO
    devices:
        - "/dev/mem:/dev/mem"
        - "/dev/gpiomem:/dev/gpiomem"
        - "/dev/i2c-1:/dev/i2c-1"
        - "/dev/ttyUSB0:/dev/ttyUSB0"

  # ------------------------------------------------------------------------------------
  # Grafana
  # ------------------------------------------------------------------------------------
  grafana:
    image: grafana/grafana
    restart: unless-stopped
    network_mode: host
    ports:
      - '3000:3000'
    volumes:
        - "grafana-data:/data"

  
volumes:
  hivemq_data:
  hivemq_log:
  hivemq_license:
  node-red-data:
  grafana-data:
  influxdb-data:
  influxdb-etc:
